### ISSUE TITLE
NullPointerException with P8Lite and API 21 

### ISSUE THREAD

**Issue by mdenhartog** [moldedbits/r2d2#5]
With API 21 I get the following NullPointerException. Other versions of the API are working correctly.

Simply executing the following code :

R2d2 r2d2 = new R2d2(getApplicationContext());

// Save token encrypted
String encrypted = r2d2.encryptData("testToken");

10-31 01:23:05.538: E/AndroidRuntime(22861): java.lang.NullPointerException: chain == null
10-31 01:23:05.538: E/AndroidRuntime(22861): 	at java.security.KeyStore$PrivateKeyEntry.<init>(KeyStore.java:1206)
10-31 01:23:05.538: E/AndroidRuntime(22861): 	at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:374)
10-31 01:23:05.538: E/AndroidRuntime(22861): 	at java.security.KeyStore.getEntry(KeyStore.java:645)
10-31 01:23:05.538: E/AndroidRuntime(22861): 	at com.moldedbits.r2d2.R2d2.encryptDataJ(R2d2.java:259)
10-31 01:23:05.538: E/AndroidRuntime(22861): 	at com.moldedbits.r2d2.R2d2.encryptData(R2d2.java:226)
10-31 01:23:05.538: E/AndroidRuntime(22861): 	at

**Comment by BethNash2029** [comment]
My own personal information and details for my own personal email address an phone number to my personal information and details on what I need to do for this entire process of the company and the following services an links of the company I'm using for this site and the other information about it and how to use it for free on the website and my personal email address and phone number for the following Google Chrome browser I'm using for my own personal account and personal phone number and email account for the same reason you did something that I am in need to get back on the list of things that I am going through with this entire process of the company and the phone number and email account for me to use as well as get my personal information  I need to know about it all. If you want to use search engine optimization for free of charge to the following Google account and personal phone number and email address for free of all the information and details of the entire program and my own personal information and details in english
